Repository fieldstyler/TennisStink, pull requests merged in 2021-02, with the labels that each got.

#8 Models
  app/models/match.rb
  app/models/player.rb
  spec/models/match_spec.rb
  spec/models/player_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: Author Needs Review, Author Thinks Ready To Merge, BE, New Feature

#10 Spec setup
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: Reviewer Thinks Ready To Merge

#11 Create and run migrations for players and matches
  db/migrate/20210209201402_create_players.rb
  db/migrate/20210209202318_create_matches.rb
  db/schema.rb
Labels: Author Thinks Ready To Merge, BE
